apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cos-fleetshard-connectors-camel
  labels:
    app: rhoc
spec:
  selector:
    matchLabels:
      cos.bf2.org/operator.type: "camel-connector-operator"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /q/metrics
      port: http
