apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: rhoc
  name: camel-k-operator-rules
spec:
  groups:
    - name: camel-k-operator
      rules:
        - alert: CamelKOperatorTargetDown
          expr: up{container="camel-k-operator"} !=1 or absent(up{container="camel-k-operator"})
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: 'The camel-k operator target is down'
            description: 'The camel-k operator target has been unable to sync the {{ $labels.container }} container in the {{ $labels.namespace }} namespace for longer than 10 minutes'
            sop_url: 'https://TODO'
        - alert: CamelKOperatorContainerFrequentlyRestarting
          expr: increase(kube_pod_container_status_restarts_total{container="camel-k-operator"}[60m]) > 3
          labels:
            severity: warning
          annotations:
            summary: 'the camel-k operator is restarting frequently'
            description: 'the camel-k operator container restarted frequently in the last 60 minutes'
            sop_url: 'https://TODO'
        - alert: CamelKReconciliationDuration
          expr: |
            (
            1 - sum(rate(camel_k_reconciliation_duration_seconds_bucket{le="0.5"}[5m])) by (job)
            /
            sum(rate(camel_k_reconciliation_duration_seconds_count[5m])) by (job)
            )
            * 100
            > 10
          for: 1m
          labels:
            severity: warning
          annotations:
            message: |
              {{ printf "%0.0f" $value }}% of the reconciliation requests
              for {{ $labels.job }} have their duration above 0.5s.
        - alert: CamelKReconciliationFailure
          expr: |
            sum(rate(camel_k_reconciliation_duration_seconds_count{result="Errored"}[5m])) by (job)
            /
            sum(rate(camel_k_reconciliation_duration_seconds_count[5m])) by (job)
            * 100
            > 1
          for: 10m
          labels:
            severity: warning
          annotations:
            message: |
              {{ printf "%0.0f" $value }}% of the reconciliation requests
              for {{ $labels.job }} have failed.