match[]:
  - 'console_url'
  - 'cluster_version'
  - 'subscription_sync_total'
  - 'kube_node_labels'
  - 'kube_persistentvolume_capacity_bytes'
  - 'kubelet_volume_stats_used_bytes{endpoint="https-metrics",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - 'kubelet_volume_stats_available_bytes{endpoint="https-metrics",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - 'kubelet_volume_stats_capacity_bytes{endpoint="https-metrics",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - 'kubelet_volume_stats_inodes{endpoint="https-metrics",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - 'kubelet_volume_stats_inodes_used{endpoint="https-metrics",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - 'kube_pod_container_status_restarts_total{namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - 'kube_pod_container_status_ready{namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - 'haproxy_server_bytes_in_total{endpoint="metrics",job!="router-internal-default"}'
  - 'haproxy_server_bytes_out_total{endpoint="metrics",job!="router-internal-default"}'
  - 'haproxy_backend_connections_total{endpoint="metrics",job!="router-internal-default"}'
  - 'haproxy_backend_connection_errors_total{endpoint="metrics",job!="router-internal-default"}'
  - '{__name__=~"kube_pod_info|kube_pod_container_resource_.*|kube_resourcequota|kube_pod_container_info|kube_namespace_created|kube_namespace_status_phase|kube_namespace_labels|kube_persistentvolumeclaim_status_condition|kube_persistentvolumeclaim_info|kube_persistentvolumeclaim_resource_requests_storage_bytes",service="kube-state-metrics",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - '{__name__="node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - '{__name__=~"node:.*"}'
  - '{__name__=~"instance:.*",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - '{__name__=~"container_memory_cache|container_memory_rss|container_memory_swap|container_memory_working_set_bytes|container_memory_usage_bytes",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - '{__name__=~"container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_usage_seconds_total",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - '{__name__="container_last_seen",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - '{__name__=~":node_memory_.*"}'
  - '{__name__=~"csv_.*"}'
  - '{__name__=~"node_.*",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'
  - '{__name__=~"container_network_receive_bytes_total|container_network_receive_packets_dropped_total|container_network_receive_packets_total|container_network_transmit_packets_dropped_total|container_network_transmit_bytes_total|container_network_transmit_packets_total",namespace!~"openshift-.*$",namespace!~"kube-.*$",namespace!="default"}'